name: Test Check Run
on:
  check_run:
    types: [created, completed]
  check_suite: {}
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
