name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed, labeled, unlabeled]
jobs:
  output-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-explore-debug@master
