name: Debug
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, review_requested]
  pull_request_review:
    types: [submitted]
jobs:
  output-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-explore-debug@master
