name: Debug
on:
  push: {}
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-explore-debug@master
        with:
          jq_selector: ".pull_request"
