name: Issue Management
on:
  pull_request:
    types: [opened, closed, review_requested]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
jobs:
  issue-management:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-issue-management@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
