name: Test
on:
  pull_request:
    types: [opened, synchronize, closed, labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.repos.getCollaboratorPermissionLevel({
              owner: "mheap",
              repo: "action-test",
              username: "mheap"
            })
            console.log(result)
            
